### ISSUE TITLE
Hi! 

### ISSUE THREAD

**Issue by SleNdd** [bennett-sh/schemas#2]
Hi! I would like to get "We Maid Pro Unlocker" somehow, but this repository is blocked. I didn't find it in other sources. I didn't find your contacts, except for github, either. How can I contact you? Could you please provide me with "WeMod Pro Unlocker"?

**Comment by bennett-sh** [comment]
Hey, thanks for the interest however because I don't want to get into any
further legal trouble, I will not continue on distributing the requested
piece of software again.

**Comment by SleNdd** [comment]
Oh, it's sad, I really wanted to get this unlocker :( Okay. Thanks for the reply.

**Comment by bennett-sh** [comment]
Have you searched on GitHub though? I think there may still be some forks however I advise you to not use them unless you have explicit permission by WeMod.

**Comment by SleNdd** [comment]
Well, I live in Russia, an ordinary unknown student, so I'm unlikely to have problems with the authors of WeMod :)
https://vscode.githubhelp.com/bennett-sh/wemod-pro-unlocker
I managed to find something, but I can't compile it.
